/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesCorporateRelocationRouteImport } from './routes/services.corporate-relocation'
import { Route as ServicesHouseholdShiftingRouteImport } from './routes/services.household-shifting'
import { Route as ServicesIntercityInterstateRouteImport } from './routes/services.intercity-interstate'
import { Route as ServicesVehicleTransportationRouteImport } from './routes/services.vehicle-transportation'
import { Route as ServicesWarehousingRouteImport } from './routes/services.warehousing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCorporateRelocationRoute =
  ServicesCorporateRelocationRouteImport.update({
    id: '/corporate-relocation',
    path: '/corporate-relocation',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesHouseholdShiftingRoute =
  ServicesHouseholdShiftingRouteImport.update({
    id: '/household-shifting',
    path: '/household-shifting',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesIntercityInterstateRoute =
  ServicesIntercityInterstateRouteImport.update({
    id: '/intercity-interstate',
    path: '/intercity-interstate',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesVehicleTransportationRoute =
  ServicesVehicleTransportationRouteImport.update({
    id: '/vehicle-transportation',
    path: '/vehicle-transportation',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesWarehousingRoute = ServicesWarehousingRouteImport.update({
  id: '/warehousing',
  path: '/warehousing',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/corporate-relocation': typeof ServicesCorporateRelocationRoute
  '/services/household-shifting': typeof ServicesHouseholdShiftingRoute
  '/services/intercity-interstate': typeof ServicesIntercityInterstateRoute
  '/services/vehicle-transportation': typeof ServicesVehicleTransportationRoute
  '/services/warehousing': typeof ServicesWarehousingRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/services/corporate-relocation': typeof ServicesCorporateRelocationRoute
  '/services/household-shifting': typeof ServicesHouseholdShiftingRoute
  '/services/intercity-interstate': typeof ServicesIntercityInterstateRoute
  '/services/vehicle-transportation': typeof ServicesVehicleTransportationRoute
  '/services/warehousing': typeof ServicesWarehousingRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/corporate-relocation': typeof ServicesCorporateRelocationRoute
  '/services/household-shifting': typeof ServicesHouseholdShiftingRoute
  '/services/intercity-interstate': typeof ServicesIntercityInterstateRoute
  '/services/vehicle-transportation': typeof ServicesVehicleTransportationRoute
  '/services/warehousing': typeof ServicesWarehousingRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/pricing'
    | '/services'
    | '/services/corporate-relocation'
    | '/services/household-shifting'
    | '/services/intercity-interstate'
    | '/services/vehicle-transportation'
    | '/services/warehousing'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/pricing'
    | '/services/corporate-relocation'
    | '/services/household-shifting'
    | '/services/intercity-interstate'
    | '/services/vehicle-transportation'
    | '/services/warehousing'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/pricing'
    | '/services'
    | '/services/corporate-relocation'
    | '/services/household-shifting'
    | '/services/intercity-interstate'
    | '/services/vehicle-transportation'
    | '/services/warehousing'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  PricingRoute: typeof PricingRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/corporate-relocation': {
      id: '/services/corporate-relocation'
      path: '/corporate-relocation'
      fullPath: '/services/corporate-relocation'
      preLoaderRoute: typeof ServicesCorporateRelocationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/household-shifting': {
      id: '/services/household-shifting'
      path: '/household-shifting'
      fullPath: '/services/household-shifting'
      preLoaderRoute: typeof ServicesHouseholdShiftingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/intercity-interstate': {
      id: '/services/intercity-interstate'
      path: '/intercity-interstate'
      fullPath: '/services/intercity-interstate'
      preLoaderRoute: typeof ServicesIntercityInterstateRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/vehicle-transportation': {
      id: '/services/vehicle-transportation'
      path: '/vehicle-transportation'
      fullPath: '/services/vehicle-transportation'
      preLoaderRoute: typeof ServicesVehicleTransportationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/warehousing': {
      id: '/services/warehousing'
      path: '/warehousing'
      fullPath: '/services/warehousing'
      preLoaderRoute: typeof ServicesWarehousingRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesCorporateRelocationRoute: typeof ServicesCorporateRelocationRoute
  ServicesHouseholdShiftingRoute: typeof ServicesHouseholdShiftingRoute
  ServicesIntercityInterstateRoute: typeof ServicesIntercityInterstateRoute
  ServicesVehicleTransportationRoute: typeof ServicesVehicleTransportationRoute
  ServicesWarehousingRoute: typeof ServicesWarehousingRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCorporateRelocationRoute: ServicesCorporateRelocationRoute,
  ServicesHouseholdShiftingRoute: ServicesHouseholdShiftingRoute,
  ServicesIntercityInterstateRoute: ServicesIntercityInterstateRoute,
  ServicesVehicleTransportationRoute: ServicesVehicleTransportationRoute,
  ServicesWarehousingRoute: ServicesWarehousingRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  PricingRoute: PricingRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
